apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
    monitoring: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: kvmayer/go-bff:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: RECRUITMENTS_ADDRESS
              value: recruitments:9090
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  labels:
    app: bff
spec:
  selector:
    app: bff
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---