apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: kvmayer/go-bff:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RECRUITMENTS_ADDRESS
              value: recruitments:9090
---
apiVersion: v1
kind: Service
metadata:
  name: bff
spec:
  selector:
    app: bff
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
